version: "3.8"
services:
  nginx:
    container_name: nginx
    build: ./nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ../public:/var/www/html
  php:
    container_name: php
    build: ./php
    volumes:
      - ../public:/var/www/html
    working_dir: /var/www/html